version: "1.0"

services:
  ollama-test:
    image: ghcr.io/open-webui/open-webui:ollama
    pull_policy: IfNotPresent
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
profiles:
  name: ollama-testing
  duration: 1h
  mode: provider
  tier:
    - community
  compute:
    ollama-test:
      resources:
        cpu:
          units: 16
        memory:
          size: 64Gi
        storage:
          - size: 500Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx6000-ada
  placement:
    westcoast:
      attributes:
      pricing:
        ollama-test:
          token: CST
          amount: 5

deployment:
  ollama-test:
    westcoast:
      profile: ollama-test
      count: 1